version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: blood_bank
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mySQL
      - MYSQL_DATABASE=blood_bank_v2
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
