version: '3.9'

services:
 db:
   image: mysql:latest
   restart: always
   container_name: my_container_name
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=
   volumes:
     - mysql:/var/lib/mysql

volumes:
  mysql:
