version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: blood_bank
    ports:
      - "3306:3306"
    env_file:
      - .env.local
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
