export enum Municipal {
    // Koshi Province:

    // BhojpurARUN_RURAL_MUNICIPALITY = "Arun Rural Municipality",
    AAMCHOWK_RURAL_MUNICIPALITY = "Aamchowk Rural Municipality",
    HATUWAGADHI_RURAL_MUNICIPALITY = "Hatuwagadhi Rural Municipality",
    PAUWADUNGMA_RURAL_MUNICIPALITY = "Pauwadungma Rural Municipality",
    TEMKEMAIYUNG_RURAL_MUNICIPALITY = "Temkemaiyung Rural Municipality",
    SALPASILICHHO_RURAL_MUNICIPALITY = "Salpasilichho Rural Municipality",
    RAMPRASAD_RAI_RURAL_MUNICIPALITY = "Ramprasad Rai Rural Municipality",
    SHADANANDA_MUNICIPALITY = "Shadananda Municipality",
    BHOJPUR_MUNICIPALITY = "Bhojpur Municipality",

    // Dhankuta
    CHAUBISE_RURAL_MUNICIPALITY = "Chaubise Rural Municipality",
    SHAHIDBHUMI_RURAL_MUNICIPALITY = "Shahidbhumi Rural Municipality",
    SANGURIGADHI_RURAL_MUNICIPALITY = "Sangurigadhi Rural Municipality",
    CHHATHAR_JORPATI_RURAL_MUNICIPALITY = "Chhathar Jorpati Rural Municipality",
    PAKHRIBAS_MUNICIPALITY = "Pakhribas Municipality",
    // MAHALAXMI_MUNICIPALITY = "Mahalaxmi Municipality", // also in lalitpur district
    DHANKUTA_MUNICIPALITY = "Dhankuta Municipality",

    // Ilam
    RONG_RURAL_MUNICIPALITY = "Rong Rural Municipality",
    MANGSEBUNG_RURAL_MUNICIPALITY = "Mangsebung Rural Municipality",
    CHULACHULI_RURAL_MUNICIPALITY = "Chulachuli Rural Municipality",
    SANDAKPUR_RURAL_MUNICIPALITY = "Sandakpur Rural Municipality",
    FAKPHOKTHUM_RURAL_MUNICIPALITY = "Fakphokthum Rural Municipality",
    MAIJOGMAI_RURAL_MUNICIPALITY = "Maijogmai Rural Municipality",
    ILLAM_MUNICIPALITY = "Illam Municipality",
    MAI_MUNICIPALITY = "Mai Municipality",
    DEUMAI_MUNICIPALITY = "Deumai Municipality",
    SURYODAYA_MUNICIPALITY = "Suryodaya Municipality",

    // Jhapa
    KAMAL_RURAL_MUNICIPALITY = "Kamal Rural Municipality",
    JHAPA_RURAL_MUNICIPALITY = "Jhapa Rural Municipality",
    KACHANKAWAL_RURAL_MUNICIPALITY = "Kachankawal Rural Municipality",
    GAURIGANJ_RURAL_MUNICIPALITY = "Gauriganj Rural Municipality",
    BARHADASHI_RURAL_MUNICIPALITY = "Barhadashi Rural Municipality",
    HALDIBARI_RURAL_MUNICIPALITY = "Haldibari Rural Municipality",
    BUDDHASHANTI_RURAL_MUNICIPALITY = "Buddhashanti Rural Municipality",
    SHIVASATAXI_MUNICIPALITY = "Shivasataxi Municipality",
    BHADRAPUR_MUNICIPALITY = "Bhadrapur Municipality",
    KANKAI_MUNICIPALITY = "Kankai Municipality",
    BIRTAMOD_MUNICIPALITY = "Birtamod Municipality",
    MECHINAGAR_MUNICIPALITY = "Mechinagar Municipality",
    DAMAK_MUNICIPALITY = "Damak Municipality",
    ARJUNDHARA_MUNICIPALITY = "Arjundhara Municipality",
    GAURADHAHA_MUNICIPALITY = "Gauradhaha Municipality",

    // Khotang
    SAKELA_RURAL_MUNICIPALITY = "Sakela Rural Municipality",
    KHOTEHANG_RURAL_MUNICIPALITY = "Khotehang Rural Municipality",
    BARAHAPOKHARI_RURAL_MUNICIPALITY = "Barahapokhari Rural Municipality",
    AINSELUKHARK_RURAL_MUNICIPALITY = "Ainselukhark Rural Municipality",
    RAWA_BESI_RURAL_MUNICIPALITY = "Rawa Besi Rural Municipality",
    KEPILASAGADHI_RURAL_MUNICIPALITY = "Kepilasagadhi Rural Municipality",
    JANTEDHUNGA_RURAL_MUNICIPALITY = "Jantedhunga Rural Municipality",
    DIPRUNG_CHUICHUMMA_RURAL_MUNICIPALITY = "Diprung Chuichumma Rural Municipality",
    HALESI_TUWACHUNG_MUNICIPALITY = "Halesi Tuwachung Municipality",
    DIKTEL_RUPAKOT_MAJHUWAGADHI_MUNICIPALITY = "Diktel Rupakot Majhuwagadhi Municipality",

    // Morang
    JAHADA_RURAL_MUNICIPALITY = "Jahada Rural Municipality",
    KATAHARI_RURAL_MUNICIPALITY = "Katahari Rural Municipality",
    GRAMTHAN_RURAL_MUNICIPALITY = "Gramthan Rural Municipality",
    DHANPALTHAN_RURAL_MUNICIPALITY = "Dhanpalthan Rural Municipality",
    KERABARI_RURAL_MUNICIPALITY = "Kerabari Rural Municipality",
    BUDHIGANGA_RURAL_MUNICIPALITY = "Budhiganga Rural Municipality",
    KANEPOKHARI_RURAL_MUNICIPALITY = "Kanepokhari Rural Municipality",
    LETANG_MUNICIPALITY = "Letang Municipality",
    SUNWARSHI_MUNICIPALITY = "Sunwarshi Municipality",
    RANGELI_MUNICIPALITY = "Rangeli Municipality",
    PATAHRISHANISHCHARE_MUNICIPALITY = "Patahrishanishchare Municipality",
    BIRATNAGAR_METROPOLITIAN_CITY = "Biratnagar Metropolitian City",
    URALABARI_MUNICIPALITY = "Uralabari Municipality",
    BELBARI_MUNICIPALITY = "Belbari Municipality",
    SUNDARHARAICHA_MUNICIPALITY = "Sundarharaicha Municipality",
    RATUWAMAI_MUNICIPALITY = "Ratuwamai Municipality",

    // Okhaldhunga
    SIDDHICHARAN_MUNICIPALITY = "Siddhicharan Municipality",
    CHAMPADEVI_RURAL_MUNICIPALITY = "Champadevi Rural Municipality",
    // SUNKOSHI_RURAL_MUNICIPALITY = "Sunkoshi Rural Municipality", // also in Sindhuli district
    // LIKHU_RURAL_MUNICIPALITY = "Likhu Rural Municipality", // also in Nuwakot district
    CHISANKHUGADHI_RURAL_MUNICIPALITY = "Chisankhugadhi Rural Municipality",
    MOLUNG_RURAL_MUNICIPALITY = "Molung Rural Municipality",
    KHIJIDEMBA_RURAL_MUNICIPALITY = "Khijidemba Rural Municipality",
    MANEBHANJYANG_RURAL_MUNICIPALITY = "Manebhanjyang Rural Municipality",

    // Panchthar
    YANGWARAK_RURAL_MUNICIPALITY = "Yangwarak Rural Municipality",
    HILIHANG_RURAL_MUNICIPALITY = "Hilihang Rural Municipality",
    FALELUNG_RURAL_MUNICIPALITY = "Falelung Rural Municipality",
    TUMBWEWA_RURAL_MUNICIPALITY = "Tumbewa Rural Municipality",
    KUMMAYAK_RURAL_MUNICIPALITY = "Kummayak Rural Municipality",
    MIKLAJUNG_RURAL_MUNICIPALITY = "Miklajung Rural Municipality",
    FALGUNANDA_RURAL_MUNICIPALITY = "Falgunanda Rural Municipality",
    PHIDIM_MUNICIPALITY = "Phidim Municipality",

    // Sankhuwasabha
    MAKALU_RURAL_MUNICIPALITY = "Makalu Rural Municipality",
    CHICHILA_RURAL_MUNICIPALITY = "Chichila Rural Municipality",
    SILICHONG_RURAL_MUNICIPALITY = "Silichong Rural Municipality",
    BHOTKHOLA_RURAL_MUNICIPALITY = "Bhotkhola Rural Municipality",
    SABHAPOKHARI_RURAL_MUNICIPALITY = "Sabhapokhari Rural Municipality",
    DHARMADEVI_MUNICIPALITY = "Dharmadevi Municipality",
    MADI_MUNICIPALITY = "Madi Municipality",
    PANCHAKHAPAN_MUNICIPALITY = "Panchakhapan Municipality",
    CHAINPUR_MUNICIPALITY = "Chainpur Municipality",
    KHANDBARI_MUNICIPALITY = "Khandbari Municipality",

    // Solukhumbu
    SOTANG_RURAL_MUNICIPALITY = "Sotang Rural Municipality",
    MAHAKULUNG_RURAL_MUNICIPALITY = "Mahakulung Rural Municipality",
    LIKHUPIKE_RURAL_MUNICIPALITY = "Likhupike Rural Municipality",
    NECHASALYAN_RURAL_MUNICIPALITY = "Nechasalyan Rural Municipality",
    THULUNG_DUDHKOSHI_RURAL_MUNICIPALITY = "Thulung Dudhkoshi Rural Municipality",
    MAAPYA_DUDHKOSHI_RURAL_MUNICIPALITY = "Maapya Dudhkoshi Rural Municipality",
    KHUMBUPASANGLAHMU_RURAL_MUNICIPALITY = "Khumbupasanglahmu Rural Municipality",
    SOLUDUDHAKUNDA_MUNICIPALITY = "Solududhakunda Municipality",

    // Sunsari
    GADHI_RURAL_MUNICIPALITY = "Gadhi Rural Municipality",
    KOSHI_RURAL_MUNICIPALITY = "Koshi Rural Municipality",
    BARJU_RURAL_MUNICIPALITY = "Barju Rural Municipality",
    HARINAGAR_RURAL_MUNICIPALITY = "Harinagar Rural Municipality",
    DEWANGANJ_RURAL_MUNICIPALITY = "Dewanganj Rural Municipality",
    BHOKRAHA_NARSING_RURAL_MUNICIPALITY = "Bhokraha Narsing Rural Municipality",
    RAMDHUNI_MUNICIPALITY = "Ramdhuni Municipality",
    BARAHCHHETRA_MUNICIPALITY = "Barahchhetra Municipality",
    DUHABI_MUNICIPALITY = "Duhabi Municipality",
    INARUWA_MUNICIPALITY = "Inaruwa Municipality",
    DHARAN_SUB_METROPOLITIAN_CITY = "Dharan Sub-Metropolitan City",
    ITAHARI_SUB_METROPOLITIAN_CITY = "Itahari Sub-Metropolitan City",

    // Taplejung 
    SIDINGBA_RURAL_MUNICIPALITY = "Sidingba Rural Municipality",
    MERINGDEN_RURAL_MUNICIPALITY = "Meringden Rural Municipality",
    MAIWAKHOLA_RURAL_MUNICIPALITY = "Maiwakhola Rural Municipality",
    PHAKTANGLUNG_RURAL_MUNICIPALITY = "Phaktanglung Rural Municipality",
    SIRIJANGHA_RURAL_MUNICIPALITY = "Sirijangha Rural Municipality",
    MIKWAKHOLA_RURAL_MUNICIPALITY = "Mikwakhola Rural Municipality",
    AATHRAI_TRIBENI_RURAL_MUNICIPALITY = "Aathrai Tribeni Rural Municipality",
    PATHIVARA_YANGWARAK_RURAL_MUNICIPALITY = "Pathivara Yangwarak Rural Municipality",
    PHUNGLING_MUNICIPALITY = "Phungling Municipality",

    // Tehrathum
    CHHATHAR_RURAL_MUNICIPALITY = "Chhathar Rural Municipality",
    PHEDAP_RURAL_MUNICIPALITY = "Phedap Rural Municipality",
    AATHRAI_RURAL_MUNICIPALITY = "Aathrai Rural Municipality",
    MENCHAYAM_RURAL_MUNICIPALITY = "Menchayam Rural Municipality",
    LALIGURANS_MUNICIPALITY = "Laligurans Municipality",
    MYANGLUNG_MUNICIPALITY = "Myanglung Municipality",

    // Udayapur
    TAPLI_RURAL_MUNICIPALITY = "Tapli Rural Municipality",
    RAUTAMAI_RURAL_MUNICIPALITY = "Rautamai Rural Municipality",
    UDAYAPURGADHI_RURAL_MUNICIPALITY = "Udayapurgadhi Rural Municipality",
    LIMCHUNGBUNG_RURAL_MUNICIPALITY = "Limchungbung Rural Municipality",
    CHAUDANDIGADHI_MUNICIPALITY = "Chaudandigadhi Municipality",
    TRIYUGA_MUNICIPALITY = "Triyuga Municipality",
    KATARI_MUNICIPALITY = "Katari Municipality",
    BELAKA_MUNICIPALITY = "Belaka Municipality",


    // Madhesh Pradesh:

    // Sarlahi
    DHANKAUL_RURAL_MUNICIPALITY = "Dhankaul Rural Municipality",
    PARSA_RURAL_MUNICIPALITY = "Parsa Rural Municipality",
    BISHNU_RURAL_MUNICIPALITY = "Bishnu Rural Municipality",
    RAMNAGAR_RURAL_MUNICIPALITY = "Ramnagar Rural Municipality",
    KAUDENA_RURAL_MUNICIPALITY = "Kaudena Rural Municipality",
    BASBARIYA_RURAL_MUNICIPALITY = "Basbariya Rural Municipality",
    CHANDRANAGAR_RURAL_MUNICIPALITY = "Chandranagar Rural Municipality",
    CHAKRAGHATTA_RURAL_MUNICIPALITY = "Chakraghatta Rural Municipality",
    BRAMHAPURI_RURAL_MUNICIPALITY = "Bramhapuri Rural Municipality",
    BARAHATHAWA_MUNICIPALITY = "Barahathawa Municipality",
    HARIPUR_MUNICIPALITY = "Haripur Municipality",
    ISHWORPUR_MUNICIPALITY = "Ishworpur Municipality",
    LALBANDI_MUNICIPALITY = "Lalbandi Municipality",
    MALANGAWA_MUNICIPALITY = "Malangawa Municipality",
    KABILASI_MUNICIPALITY = "Kabilasi Municipality",
    BAGMATI_MUNICIPALITY = "Bagmati Municipality",
    HARIWAN_MUNICIPALITY = "Hariwan Municipality",
    BALARA_MUNICIPALITY = "Balara Municipality",
    HARIPURWA_MUNICIPALITY = "Haripurwa Municipality",
    GODAITA_MUNICIPALITY = "Godaita Municipality",

    // Dhanusha
    AAURAHI_RURAL_MUNICIPALITY = "Aaurahi Rural Municipality",
    DHANAUJI_RURAL_MUNICIPALITY = "Dhanauji Rural Municipality",
    BATESHWOR_RURAL_MUNICIPALITY = "Bateshwor Rural Municipality",
    JANAKNANDANI_RURAL_MUNICIPALITY = "Janaknandani Rural Municipality",
    LAKSHMINIYA_RURAL_MUNICIPALITY = "Lakshminiya Rural Municipality",
    MUKHIYAPATTI_MUSARMIYA_RURAL_MUNICIPALITY = "Mukhiyapatti Musarmiya Rural Municipality",
    MITHILA_BIHARI_MUNICIPALITY = "Mithila Bihari Municipality",
    KAMALA_MUNICIPALITY = "Kamala Municipality",
    NAGARAIN_MUNICIPALITY = "Nagarain Municipality",
    GANESMAN_CHARNATH_MUNICIPALITY = "Ganeshman Charnath Municipality",
    MITHILA_MUNICIPALITY = "Mithila Municipality",
    DHANUSADHAM_MUNICIPALITY = "Dhanusadham Municipality",
    BIDEHA_MUNICIPALITY = "Bideha Municipality",
    SABAILA_MUNICIPALITY = "Sabaila Municipality",
    HANSAPUR_MUNICIPALITY = "Hansapur Municipality",
    JANAKPURDHAM_SUB_METROPOLITIAN_CITY = "Janakpurdham Sub-Metropolitan City",
    SAHIDNAGAR_MUNICIPALITY = "Sahidnagar Municipality",
    CHHIRESHWORNATH_MUNICIPALITY = "Chhireshwornath Municipality",

    // Bara
    PHETA_RURAL_MUNICIPALITY = "Pheta Rural Municipality",
    DEVTAL_RURAL_MUNICIPALITY = "Devtal Rural Municipality",
    PRASAUNI_RURAL_MUNICIPALITY = "Prasauni Rural Municipality",
    SUWARNA_RURAL_MUNICIPALITY = "Suwarna Rural Municipality",
    BARAGADHI_RURAL_MUNICIPALITY = "Baragadhi Rural Municipality",
    KARAIYAMAI_RURAL_MUNICIPALITY = "Karaiyamai Rural Municipality",
    PARWANIPUR_RURAL_MUNICIPALITY = "Parwanipur Rural Municipality",
    BISHRAMPUR_RURAL_MUNICIPALITY = "Bishrampur Rural Municipality",
    ADARSHKOTWAL_RURAL_MUNICIPALITY = "Adarshkotwal Rural Municipality",
    JITPUR_SIMARA_SUB_METROPOLITIAN_CITY = "Jitpur Simara Sub-Metropolitan City",
    KALAIYA_SUB_METROPOLITIAN_CITY = "Kalaiya Sub-Metropolitan City",
    PACHARAUTA_MUNICIPALITY = "Pacharauta Municipality",
    NIJGADH_MUNICIPALITY = "Nijgadh Municipality",
    SIMRAUNGADH_MUNICIPALITY = "Simraungadh Municipality",
    MAHAGADHIMAI_MUNICIPALITY = "Mahagadhimai Municipality",
    KOLHABI_MUNICIPALITY = "Kolhabi Municipality",

    // Rautahat
    YEMUNAMAI_RURAL_MUNICIPALITY = "Yemunamai Rural Municipality",
    DURGA_BHAGWATI_RURAL_MUNICIPALITY = "Durga Bhagwati Rural Municipality",
    KATAHARIYA_MUNICIPALITY = "Katahariya Municipality",
    MAULAPUR_MUNICIPALITY = "Maulapur Municipality",
    MADHAV_NARAYAN_MUNICIPALITY = "Madhav Narayan Municipality",
    GAUR_MUNICIPALITY = "Gaur Municipality",
    GUJARA_MUNICIPALITY = "Gujara Municipality",
    GARUDA_MUNICIPALITY = "Garuda Municipality",
    ISHANATH_MUNICIPALITY = "Ishanath Municipality",
    CHANDRAPUR_MUNICIPALITY = "Chandrapur Municipality",
    DEWAHHI_GONAHI_MUNICIPALITY = "Dewahhi Gonahi Municipality",
    BRINDABAN_MUNICIPALITY = "Brindaban Municipality",
    RAJPUR_MUNICIPALITY = "Rajpur Municipality",
    RAJDEVI_MUNICIPALITY = "Rajdevi Municipality",
    GADHIMAI_MUNICIPALITY = "Gadhimai Municipality",
    PHATUWA_BIJAYAPUR_MUNICIPALITY = "Phatuwa Bijayapur Municipality",
    BAUDHIMAI_MUNICIPALITY = "Baudhimai Municipality",
    PAROHA_MUNICIPALITY = "Paroha Municipality",

    // Saptari
    RAJGADH_RURAL_MUNICIPALITY = "Rajgadh Rural Municipality",
    RUPANI_RURAL_MUNICIPALITY = "Rupani Rural Municipality",
    TIRAHUT_RURAL_MUNICIPALITY = "Tirahut Rural Municipality",
    MAHADEVA_RURAL_MUNICIPALITY = "Mahadeva Rural Municipality",
    BISHNUPUR_RURAL_MUNICIPALITY = "Bishnupur Rural Municipality",
    CHHINNAMASTA_RURAL_MUNICIPALITY = "Chhinnamasta Rural Municipality",
    BALAN_BIHUL_RURAL_MUNICIPALITY = "Balan Bihul Rural Municipality",
    TILATHI_KOILADI_RURAL_MUNICIPALITY = "Tilathi Koiladi Rural Municipality",
    AGNISAIR_KRISHNA_SAVARAN_RURAL_MUNICIPALITY = "Agnisair Krishna Savaran Rural Municipality",
    HANUMANNAGAR_KANKALINI_MUNICIPALITY = "Hanumannagar Kankalini Municipality",
    KANCHANRUP_MUNICIPALITY = "Kanchanrup Municipality",
    RAJBIRAJ_MUNICIPALITY = "Rajbiraj Municipality",
    KHADAK_MUNICIPALITY = "Khadak Municipality",
    DAKNESHWORI_MUNICIPALITY = "Dakneshwori Municipality",
    SAPTAKOSHI_RURAL_MUNICIPALITY = "Saptakoshi Rural Municipality",
    SURUNGA_MUNICIPALITY = "Surunga Municipality",
    SHAMBHUNATH_MUNICIPALITY = "Shambhunath Municipality",
    BODE_BARSAIN_MUNICIPALITY = "Bode Barsain Municipality",

    // Siraha
    AURAHI_RURAL_MUNICIPALITY = "Aurahi Rural Municipality",
    NARAHA_RURAL_MUNICIPALITY = "Naraha Rural Municipality",
    ARNAMA_RURAL_MUNICIPALITY = "Arnama Rural Municipality",
    BHAGAWANPUR_RURAL_MUNICIPALITY = "Bhagawanpur Rural Municipality",
    NAWARAJPUR_RURAL_MUNICIPALITY = "Nawarajpur Rural Municipality",
    // BISHNUPUR_RURAL_MUNICIPALITY = "Bishnupur Rural Municipality", // also in saptari
    BARIYARPATTI_RURAL_MUNICIPALITY = "Bariyarpatti Rural Municipality",
    LAXMIPUR_PATARI_RURAL_MUNICIPALITY = "Laxmipur Patari Rural Municipality",
    SAKHUWANANKARKATTI_RURAL_MUNICIPALITY = "Sakhuwanankarkatti Rural Municipality",
    MIRCHAIYA_MUNICIPALITY = "Mirchaiya Municipality",
    LAHAN_MUNICIPALITY = "Lahan Municipality",
    SIRAHA_MUNICIPALITY = "Siraha Municipality",
    DHANGADHIMAI_MUNICIPALITY = "Dhangadhimai Municipality",
    KALYANPUR_MUNICIPALITY = "Kalyanpur Municipality",
    KARJANHA_MUNICIPALITY = "Karjanha Municipality",
    GOLBAZAR_MUNICIPALITY = "Golbazar Municipality",
    SUKHIPUR_MUNICIPALITY = "Sukhipur Municipality",

    // Mahottari
    PIPRA_RURAL_MUNICIPALITY = "Pipra Rural Municipality",
    SONAMA_RURAL_MUNICIPALITY = "Sonama Rural Municipality",
    SAMSI_RURAL_MUNICIPALITY = "Samsi Rural Municipality",
    EKDANRA_RURAL_MUNICIPALITY = "Ekdandra Rural Municipality",
    MAHOTTARI_RURAL_MUNICIPALITY = "Mahottari Rural Municipality",
    GAUSHALA_MUNICIPALITY = "Gaushala Municipality",
    RAMGOPALPUR_MUNICIPALITY = "Ramgopalpur Municipality",
    AURAHI_MUNICIPALITY = "Aurahi Municipality",
    BARDIBAS_MUNICIPALITY = "Bardibas Municipality",
    BHANGAHA_MUNICIPALITY = "Bhangaha Municipality",
    JALESWOR_MUNICIPALITY = "Jaleswor Municipality",
    BALWA_MUNICIPALITY = "Balwa Municipality",
    MANRA_SISWA_MUNICIPALITY = "Manra Siswa Municipality",
    MATIHANI_MUNICIPALITY = "Matihani Municipality",
    LOHARPATTI_MUNICIPALITY = "Loharpatti Municipality",

    // Parsa
    THORI_RURAL_MUNICIPALITY = "Thori Rural Municipality",
    DHOBINI_RURAL_MUNICIPALITY = "Dhobini Rural Municipality",
    CHHIPAHARMAI_RURAL_MUNICIPALITY = "Chhipaharmai Rural Municipality",
    JIRABHAWANI_RURAL_MUNICIPALITY = "Jirabhawani Rural Municipality",
    JAGARNATHPUR_RURAL_MUNICIPALITY = "Jagarnathpur Rural Municipality",
    KALIKAMAI_RURAL_MUNICIPALITY = "Kalikamai Rural Municipality",
    BINDABASINI_RURAL_MUNICIPALITY = "Bindabasini Rural Municipality",
    PAKAHAMAINPUR_RURAL_MUNICIPALITY = "Pakahamainpur Rural Municipality",
    SAKHUWAPRASAUNI_RURAL_MUNICIPALITY = "Sakhuwaprasauni Rural Municipality",
    PATERWASUGAULI_RURAL_MUNICIPALITY = "Paterwasugauli Rural Municipality",
    BIRGUNJ_METROPOLITIAN_CITY = "Birgunj Metropolitan City",
    BAHUDARAMAI_MUNICIPALITY = "Bahudaramai Municipality",
    POKHARIYA_MUNICIPALITY = "Pokhariya Municipality",
    PARSAGADHI_MUNICIPALITY = "Parsagadhi Municipality",

    // Bagmati Pradesh

    // Sindhuli
    MARIN_RURAL_MUNICIPALITY = "Marin Rural Municipality",
    PHIKKAL_RURAL_MUNICIPALITY = "Phikkal Rural Municipality",
    TINPATAN_RURAL_MUNICIPALITY = "Tinpatan Rural Municipality",
    SUNKOSHI_RURAL_MUNICIPALITY = "Sunkoshi Rural Municipality",
    GOLANJOR_RURAL_MUNICIPALITY = "Golanjor Rural Municipality",
    GHANGLEKH_RURAL_MUNICIPALITY = "Ghanglekh Rural Municipality",
    HARIHARPURGADHI_RURAL_MUNICIPALITY = "Hariharpurgadhi Rural Municipality",
    DUDHOULI_MUNICIPALITY = "Dudhouli Municipality",
    KAMALAMAI_MUNICIPALITY = "Kamalamai Municipality",

    // Ramechhap
    MANTHALI_MUNICIPALITY = "Manthali Municipality",
    RAMECHHAP_MUNICIPALITY = "Ramechhap Municipality",
    UMAKUNDA_RURAL_MUNICIPALITY = "Umakunda Rural Municipality",
    KHANDEVI_RURAL_MUNICIPALITY = "Khandadevi Rural Municipality",
    DORAMBA_RURAL_MUNICIPALITY = "Doramba Rural Municipality",
    GOKULGANGA_RURAL_MUNICIPALITY = "Gokulganga Rural Municipality",
    LIKHUTAMAKOSHI_RURAL_MUNICIPALITY = "Likhutamakoshi Rural Municipality",
    SUNAPATI_RURAL_MUNICIPALITY = "Sunapati Rural Municipality",

    // Dolakha
    BHIMESHWOR_MUNICIPALITY = "Bhimeswor Municipality",
    JIRI_MUNICIPALITY = "Jiri Municipality",
    KALINCHOK_RURAL_MUNICIPALITY = "Kalinchok Rural Municipality",
    MELUNG_RURAL_MUNICIPALITY = "Melung Rural Municipality",
    BIGU_RURAL_MUNICIPALITY = "Bigu Rural Municipality",
    GAURISHANKAR_RURAL_MUNICIPALITY = "Gaurishankar Rural Municipality",
    BAITESHWOR_RURAL_MUNICIPALITY = "Baiteshwor Rural Municipality",
    SAILUNG_RURAL_MUNICIPALITY = "Sailung Rural Municipality",
    TAMAKOSHI_RURAL_MUNICIPALITY = "Tamakoshi Rural Municipality",

    // Bhaktapur
    CHANGUNARAYAN_MUNICIPALITY = "Changunarayan Municipality",
    SURYABINAYAK_MUNICIPALITY = "Suryabinayak Municipality",
    BHAKTAPUR_MUNICIPALITY = "Bhaktapur Municipality",
    MADHYAPUR_THIMI_MUNICIPALITY = "Madhyapur Thimi Municipality",

    // Dhading
    GAJURI_RURAL_MUNICIPALITY = "Gajuri Rural Municipality",
    GALCHI_RURAL_MUNICIPALITY = "Galchi Rural Municipality",
    THAKRE_RURAL_MUNICIPALITY = "Thakre Rural Municipality",
    SIDDHALEK_RURAL_MUNICIPALITY = "Siddhalek Rural Municipality",
    KHANIYABASH_RURAL_MUNICIPALITY = "Khaniyabash Rural Municipality",
    JWALAMUKHI_RURAL_MUNICIPALITY = "Jwalamukhi Rural Municipality",
    GANGAJAMUNA_RURAL_MUNICIPALITY = "Gangajamuna Rural Municipality",
    RUBI_VALLEY_RURAL_MUNICIPALITY = "Rubi Valley Rural Municipality",
    TRIPURA_SUNDARI_RURAL_MUNICIPALITY = "Tripura Sundari Rural Municipality",
    NETRAWATI_DABJONG_RURAL_MUNICIPALITY = "Netrawati Dabjong Rural Municipality",
    BENIGHAT_RORANG_RURAL_MUNICIPALITY = "Benighat Rorang Rural Municipality",
    NILAKANTHA_MUNICIPALITY = "Nilakantha Municipality",
    DHUNIBESI_MUNICIPALITY = "Dhunibesi Municipality",

    // Kathmandu
    KIRTIPUR_MUNICIPALITY = "Kirtipur Municipality",
    SHANKHARAPUR_MUNICIPALITY = "Shankharapur Municipality",
    NAGARJUN_MUNICIPALITY = "Nagarjun Municipality",
    KAGESHWORI_MANAHORA_MUNICIPALITY = "Kageshwori Manahora Municipality",
    DAKSHINKALI_MUNICIPALITY = "Dakshinkali Municipality",
    BUDHANILKANTHA_MUNICIPALITY = "Budhanilkantha Municipality",
    TARAKESHWOR_MUNICIPALITY = "Tarakeshwor Municipality",
    KATHMANDU_METROPOLITAN_CITY = "Kathmandu Metropolitan City",
    TOKHA_MUNICIPALITY = "Tokha Municipality",
    CHANDRAGIRI_MUNICIPALITY = "Chandragiri Municipality",
    GOKARNESHWOR_MUNICIPALITY = "Gokarneshwor Municipality",

    // Kavrepalanchok
    ROSHI_RURAL_MUNICIPALITY = "Roshi Rural Municipality",
    TEMAL_RURAL_MUNICIPALITY = "Temal Rural Municipality",
    BHUMLU_RURAL_MUNICIPALITY = "Bhumlu Rural Municipality",
    MAHABHARAT_RURAL_MUNICIPALITY = "Mahabharat Rural Municipality",
    BETHANCHOWK_RURAL_MUNICIPALITY = "Bethanchowk Rural Municipality",
    KHANIKHOLA_RURAL_MUNICIPALITY = "Khanikhola Rural Municipality",
    CHAURIDEURALI_RURAL_MUNICIPALITY = "Chaurideurali Rural Municipality",
    BANEPA_MUNICIPALITY = "Banepa Municipality",
    MANDANDEUPUR_MUNICIPALITY = "Mandan Deupur Municipality",
    DHULIKHEL_MUNICIPALITY = "Dhulikhel Municipality",
    PANAUTI_MUNICIPALITY = "Panauti Municipality",
    NAMOBUDDHA_MUNICIPALITY = "Namobuddha Municipality",
    PANCHKHAL_MUNICIPALITY = "Panchkhal Municipality",

    // Lalitpur
    BAGMATI_RURAL_MUNICIPALITY = "Bagmati Rural Municipality",
    MAHANKAL_RURAL_MUNICIPALITY = "Mahankal Rural Municipality",
    KONJYOSOM_RURAL_MUNICIPALITY = "Konjyosom Rural Municipality",
    LALITPUR_METROPOLITAN_CITY = "Lalitpur Metropolitan City",
    MAHALAXMI_MUNICIPALITY = "Mahalaxmi Municipality",
    GODAWARI_MUNICIPALITY = "Godawari Municipality",

    // Nuwakot
    KAKANI_RURAL_MUNICIPALITY = "Kakani Rural Municipality",
    TADI_RURAL_MUNICIPALITY = "Tadi Rural Municipality",
    LIKHU_RURAL_MUNICIPALITY = "Likhu Rural Municipality",
    MYAGANG_RURAL_MUNICIPALITY = "Myagang Rural Municipality",
    SHIVAPURI_RURAL_MUNICIPALITY = "Shivapuri Rural Municipality",
    KISPANG_RURAL_MUNICIPALITY = "Kispang Rural Municipality",
    SURYAGADHI_RURAL_MUNICIPALITY = "Suryagadhi Rural Municipality",
    TARKESHWAR_RURAL_MUNICIPALITY = "Tarkeshwar Rural Municipality",
    PANCHAKANYA_RURAL_MUNICIPALITY = "Panchakanya Rural Municipality",
    DUPCHESHWAR_RURAL_MUNICIPALITY = "Dupcheshwar Rural Municipality",
    BELKOTGADHI_MUNICIPALITY = "Belkotgadhi Municipality",
    BIDUR_MUNICIPALITY = "Bidur Municipality",

    // Rasuwa
    KALIKA_RURAL_MUNICIPALITY = "Kalika Rural Municipality",
    NAUKUNDA_RURAL_MUNICIPALITY = "Naukunda Rural Municipality",
    UTTARGAYA_RURAL_MUNICIPALITY = "Uttargaya Rural Municipality",
    GOSAIKUNDA_RURAL_MUNICIPALITY = "Gosaikunda Rural Municipality",
    AMACHODINGMO_RURAL_MUNICIPALITY = "Amachodingmo Rural Municipality",

    // Sindhupalchok
    JUGAL_RURAL_MUNICIPALITY = "Jugal Rural Municipality",
    BALEFI_RURAL_MUNICIPALITY = "Balefi Rural Municipality",
    // Repeating Sunkoshi Rural Municipality from the previous section
    HELAMBU_RURAL_MUNICIPALITY = "Helambu Rural Municipality",
    BHOTEKOSHI_RURAL_MUNICIPALITY = "Bhotekoshi Rural Municipality",
    LISANGKHU_PAKHAR_RURAL_MUNICIPALITY = "Lisangkhu Pakhar Rural Municipality",
    INDRAWATI_RURAL_MUNICIPALITY = "Indrawati Rural Municipality",
    TRIPURASUNDARI_RURAL_MUNICIPALITY = "Tripurasundari Rural Municipality",
    PANCHPOKHARI_THANGPAL_RURAL_MUNICIPALITY = "Panchpokhari Thangpal Rural Municipality",
    CHAUTARA_SANGACHOKGADHI_MUNICIPALITY = "Chautara Sangachokgadhi Municipality",
    BARHABISE_MUNICIPALITY = "Barhabise Municipality",
    MELAMCHI_MUNICIPALITY = "Melamchi Municipality",

    // Chitwan
    BHARATPUR_METROPOLITAN_CITY = "Bharatpur Metropolitan City",
    KALIKA_MUNICIPALITY = "Kalika Municipality",
    KHAIRAHANI_MUNICIPALITY = "Khairahani Municipality",
    // MADI_MUNICIPALITY = "Madi Municipality", // also in Sankhuwasabha district
    RATNANAGAR_MUNICIPALITY = "Ratnanagar Municipality",
    RAPTI_MUNICIPALITY = "Rapti Municipality",
    ICHCHHAKAMANA_RURAL_MUNICIPALITY = "Ichchhakamana Rural Municipality",

    // Makwanpur
    HETAUDA_SUB_METROPOLITAN_CITY = "Hetauda Sub-Metropolitan City",
    THAHA_MUNICIPALITY = "Thaha Municipality",
    BHIMPHEDI_RURAL_MUNICIPALITY = "Bhimphedi Rural Municipality",
    MAKAWANPURGADHI_RURAL_MUNICIPALITY = "Makawanpurgadhi Rural Municipality",
    MANAHARI_RURAL_MUNICIPALITY = "Manahari Rural Municipality",
    RAKSIRANG_RURAL_MUNICIPALITY = "Raksirang Rural Municipality",
    BAKAIYA_RURAL_MUNICIPALITY = "Bakaiya Rural Municipality",
    // BAGMATI_RURAL_MUNICIPALITY = "Bagmati Rural Municipality", // also in Lalitpur district
    KAILASH_RURAL_MUNICIPALITY = "Kailash Rural Municipality",
    INDRASAROWAR_RURAL_MUNICIPALITY = "Indrasarowar Rural Municipality",

    // Gandaki Province:

    // Baglung
    BARENG_RURAL_MUNICIPALITY = "Bareng Rural Municipality",
    BADIGAD_RURAL_MUNICIPALITY = "Badigad Rural Municipality",
    NISIKHOLA_RURAL_MUNICIPALITY = "Nisikhola Rural Municipality",
    KANTHEKHOLA_RURAL_MUNICIPALITY = "Kanthekhola Rural Municipality",
    TARA_KHOLA_RURAL_MUNICIPALITY = "Tara Khola Rural Municipality",
    TAMAN_KHOLA_RURAL_MUNICIPALITY = "Taman Khola Rural Municipality",
    JAIMUNI_MUNICIPALITY = "Jaimuni Municipality",
    BAGLUNG_MUNICIPALITY = "Baglung Municipality",
    GALKOT_MUNICIPALITY = "Galkot Municipality",
    DHORPATAN_MUNICIPALITY = "Dhorpatan Municipality",

    // Gorkha
    GANDAKI_RURAL_MUNICIPALITY = "Gandaki Rural Municipality",
    DHARCHE_RURAL_MUNICIPALITY = "Dharche Rural Municipality",
    AARUGHAT_RURAL_MUNICIPALITY = "Aarughat Rural Municipality",
    AJIRKOT_RURAL_MUNICIPALITY = "Ajirkot Rural Municipality",
    SAHID_LAKHAN_RURAL_MUNICIPALITY = "Sahid Lakhan Rural Municipality",
    SIRANCHOK_RURAL_MUNICIPALITY = "Siranchok Rural Municipality",
    BHIMSENTHAPA_RURAL_MUNICIPALITY = "Bhimsenthapa Rural Municipality",
    CHUM_NUBRI_RURAL_MUNICIPALITY = "Chum Nubri Rural Municipality",
    BARPAK_SULIKOT_RURAL_MUNICIPALITY = "Barpak Sulikot Rural Municipality",
    PALUNGTAR_MUNICIPALITY = "Palungtar Municipality",
    GORKHA_MUNICIPALITY = "Gorkha Municipality",

    // Kaski
    RUPA_RURAL_MUNICIPALITY = "Rupa Rural Municipality",
    MADI_RURAL_MUNICIPALITY = "Madi Rural Municipality",
    ANNAPURNA_RURAL_MUNICIPALITY = "Annapurna Rural Municipality",
    MACHHAPUCHCHHRE_RURAL_MUNICIPALITY = "Machhapuchchhre Rural Municipality",
    POKHARA_METROPOLITIAN_CITY = "Pokhara Metropolitan City",

    // Lamjung
    DORDI_RURAL_MUNICIPALITY = "Dordi Rural Municipality",
    DUDHPOKHARI_RURAL_MUNICIPALITY = "Dudhpokhari Rural Municipality",
    MARSYANGDI_RURAL_MUNICIPALITY = "Marsyangdi Rural Municipality",
    KWHOLASOTHAR_RURAL_MUNICIPALITY = "Kwholasothar Rural Municipality",
    SUNDARBAZAR_MUNICIPALITY = "Sundarbazar Municipality",
    BESISHAHAR_MUNICIPALITY = "Besishahar Municipality",
    RAINAS_MUNICIPALITY = "Rainas Municipality",
    MADHYANEPAL_MUNICIPALITY = "Madhyanepal Municipality",

    // Manang
    CHAME_RURAL_MUNICIPALITY = "Chame Rural Municipality",
    NARSHON_RURAL_MUNICIPALITY = "Narshon Rural Municipality",
    NARPA_BHUMI_RURAL_MUNICIPALITY = "Narpa Bhumi Rural Municipality",
    MANANG_INGSHYANG_RURAL_MUNICIPALITY = "Manang IngsHyang Rural Municipality",

    // Mustang
    THASANG_RURAL_MUNICIPALITY = "Thasang Rural Municipality",
    GHARAPJHONG_RURAL_MUNICIPALITY = "Gharapjhong Rural Municipality",
    LOMANTHANG_RURAL_MUNICIPALITY = "Lomanthang Rural Municipality",
    LO_GHEKAR_DAMODARKUNDA_RURAL_MUNICIPALITY = "Lo-Ghekar Damodarkunda Rural Municipality",
    WARAGUNG_MUKTIKHSETRA_RURAL_MUNICIPALITY = "Waragung Muktikhsetra Rural Municipality",

    // Myagdi
    MANGALA_RURAL_MUNICIPALITY = "Mangala Rural Municipality",
    // MALIKA_RURAL_MUNICIPALITY = "Malika Rural Municipality", // also in Gulmi
    RAGHUGANGA_RURAL_MUNICIPALITY = "Raghuganga Rural Municipality",
    DHAULAGIRI_RURAL_MUNICIPALITY = "Dhaulagiri Rural Municipality",
    //  ANNAPURNA_RURAL_MUNICIPALITY = "Annapurna Rural Municipality", // also in kaski
    BENI_MUNICIPALITY = "Beni Municipality",

    // Nawalpur
    BAUDEEKALI_RURAL_MUNICIPALITY = "Baudeekali Rural Municipality",
    BULINGTAR_RURAL_MUNICIPALITY = "Bulingtar Rural Municipality",
    HUPSEKOT_RURAL_MUNICIPALITY = "Hupsekot Rural Municipality",
    BINAYEE_TRIBENI_RURAL_MUNICIPALITY = "Binayee Tribeni Rural Municipality",
    MADHYABINDU_MUNICIPALITY = "Madhyabindu Municipality",
    DEVCHULI_MUNICIPALITY = "Devchuli Municipality",
    GAIDAKOT_MUNICIPALITY = "Gaidakot Municipality",
    KAWASOTI_MUNICIPALITY = "Kawasoti Municipality",

    // Parbat
    MODI_RURAL_MUNICIPALITY = "Modi Rural Municipality",
    PAINYU_RURAL_MUNICIPALITY = "Painyu Rural Municipality",
    JALJALA_RURAL_MUNICIPALITY = "Jaljala Rural Municipality",
    BIHADI_RURAL_MUNICIPALITY = "Bihadi Rural Municipality",
    MAHASHILA_RURAL_MUNICIPALITY = "Mahashila Rural Municipality",
    KUSHMA_MUNICIPALITY = "Kushma Municipality",
    PHALEBAS_MUNICIPALITY = "Phalebas Municipality",

    // Syangja
    HARINAS_RURAL_MUNICIPALITY = "Harinas Rural Municipality",
    BIRUWA_RURAL_MUNICIPALITY = "Biruwa Rural Municipality",
    AANDHIKHOLA_RURAL_MUNICIPALITY = "Aandhikhola Rural Municipality",
    PHEDIKHOLA_RURAL_MUNICIPALITY = "Phedikhola Rural Municipality",
    // KALIGANDAKI_RURAL_MUNICIPALITY = "Kaligandaki Rural Municipality", // also in Gulmi
    ARJUNCHAUPARI_RURAL_MUNICIPALITY = "Arjunchaupari Rural Municipality",
    PUTALIBAZAR_MUNICIPALITY = "Putalibazar Municipality",
    BHIRKOT_MUNICIPALITY = "Bhirkot Municipality",
    GALYANG_MUNICIPALITY = "Galyang Municipality",
    CHAPAKOT_MUNICIPALITY = "Chapakot Municipality",
    WALING_MUNICIPALITY = "Waling Municipality",

    // Tanahun
    GHIRING_RURAL_MUNICIPALITY = "Ghiring Rural Municipality",
    DEVGHAT_RURAL_MUNICIPALITY = "Devghat Rural Municipality",
    RHISHING_RURAL_MUNICIPALITY = "Rhishing Rural Municipality",
    MYAGDE_RURAL_MUNICIPALITY = "Myagde Rural Municipality",
    BANDIPUR_RURAL_MUNICIPALITY = "Bandipur Rural Municipality",
    ANBUKHAIRENI_RURAL_MUNICIPALITY = "Anbukhaireni Rural Municipality",
    BYAS_MUNICIPALITY = "Byas Municipality",
    SHUKLAGANDAKI_MUNICIPALITY = "Shuklagandaki Municipality",
    BHIMAD_MUNICIPALITY = "Bhimad Municipality",
    BHANU_MUNICIPALITY = "Bhanu Municipality",

    // Lumbini Province

     // Kapilvastu
     YASHODHARA_RURAL_MUNICIPALITY = "Yashodhara Rural Municipality",
     BIJAYANAGAR_RURAL_MUNICIPALITY = "Bijayanagar Rural Municipality",
     MAYADEVI_RURAL_MUNICIPALITY = "Mayadevi Rural Municipality",
     SUDDHODHAN_RURAL_MUNICIPALITY = "Suddhodhan Rural Municipality",
     SHIVARAJ_MUNICIPALITY = "Shivaraj Municipality",
     KAPILBASTU_MUNICIPALITY = "Kapilbastu Municipality",
     BUDDHABHUMI_MUNICIPALITY = "Buddhabhumi Municipality",
     MAHARAJGUNJ_MUNICIPALITY = "Maharajgunj Municipality",
     BANGANGA_MUNICIPALITY = "Banganga Municipality",
     KRISHNANAGAR_MUNICIPALITY = "Krishnanagar Municipality",
 
     // Parasi
     SARAWAL_RURAL_MUNICIPALITY = "Sarawal Rural Municipality",
     SUSTA_RURAL_MUNICIPALITY = "Susta Rural Municipality",
     PRATAPPUR_RURAL_MUNICIPALITY = "Pratappur Rural Municipality",
     PALHI_NANDAN_RURAL_MUNICIPALITY = "Palhi Nandan Rural Municipality",
     BARDAGHAT_MUNICIPALITY = "Bardaghat Municipality",
     SUNWAL_MUNICIPALITY = "Sunwal Municipality",
     RAMGRAM_MUNICIPALITY = "Ramgram Municipality",
 
     // Rupandehi
     KANCHAN_RURAL_MUNICIPALITY = "Kanchan Rural Municipality",
     SIYARI_RURAL_MUNICIPALITY = "Siyari Rural Municipality",
     ROHINI_RURAL_MUNICIPALITY = "Rohini Rural Municipality",
     GAIDAHAWA_RURAL_MUNICIPALITY = "Gaidahawa Rural Municipality",
     OMSATIYA_RURAL_MUNICIPALITY = "Omsatiya Rural Municipality",
     SUDDHDHODHAN_RURAL_MUNICIPALITY = "Suddhdhodhan Rural Municipality",
     MAYADEVI_RURAL_MUNICIPALITY_2 = "Mayadevi Rural Municipality Rupandehi",
     MARCHAWARI_RURAL_MUNICIPALITY = "Marchawari Rural Municipality",
     KOTAHIMAI_RURAL_MUNICIPALITY = "Kotahimai Rural Municipality",
     SAMMARIMAI_RURAL_MUNICIPALITY = "Sammarimai Rural Municipality",
     BUTWAL_SUB_METROPOLITAN_CITY = "Butwal Sub-Metropolitan City",
     LUMBINI_SANSKRITIK_MUNICIPALITY = "Lumbini Sanskritik Municipality",
     DEVDAHA_MUNICIPALITY = "Devdaha Municipality",
     SAINAMAINA_MUNICIPALITY = "Sainamaina Municipality",
     SIDDHARTHANAGAR_MUNICIPALITY = "Siddharthanagar Municipality",
     TILLOTAMA_MUNICIPALITY = "Tillotama Municipality",
 
     // Arghakhanchi
     PANINI_RURAL_MUNICIPALITY = "Panini Rural Municipality",
     CHHATRADEV_RURAL_MUNICIPALITY = "Chhatradev Rural Municipality",
     MALARANI_RURAL_MUNICIPALITY = "Malarani Rural Municipality",
     BHUMEKASTHAN_MUNICIPALITY = "Bhumekasthan Municipality",
     SITGANGA_MUNICIPALITY = "Sitganga Municipality",
     SANDHIKHARKA_MUNICIPALITY = "Sandhikharka Municipality",
 
     // Gulmi
     RURU_RURAL_MUNICIPALITY = "Ruru Rural Municipality",
     ISMA_RURAL_MUNICIPALITY = "Isma Rural Municipality",
     MADANE_RURAL_MUNICIPALITY = "Madane Rural Municipality",
     MALIKA_RURAL_MUNICIPALITY = "Malika Rural Municipality",
     CHATRAKOT_RURAL_MUNICIPALITY = "Chatrakot Rural Municipality",
     DHURKOT_RURAL_MUNICIPALITY = "Dhurkot Rural Municipality",
     SATYAWATI_RURAL_MUNICIPALITY = "Satyawati Rural Municipality",
     CHANDRAKOT_RURAL_MUNICIPALITY = "Chandrakot Rural Municipality",
     KALIGANDAKI_RURAL_MUNICIPALITY = "Kaligandaki Rural Municipality",
     GULMI_DARBAR_RURAL_MUNICIPALITY = "Gulmidarbar Rural Municipality",
     RESUNGA_MUNICIPALITY = "Resunga Municipality",
     MUSIKOT_MUNICIPALITY = "Musikot Municipality",
 
     // Palpa
     RAMBHA_RURAL_MUNICIPALITY = "Rambha Rural Municipality",
     TINAU_RURAL_MUNICIPALITY = "Tinau Rural Municipality",
     NISDI_RURAL_MUNICIPALITY = "Nisdi Rural Municipality",
     MATHAGADHI_RURAL_MUNICIPALITY = "Mathagadhi Rural Municipality",
     RIBDIKOT_RURAL_MUNICIPALITY = "Ribdikot Rural Municipality",
     PURBAKHOLA_RURAL_MUNICIPALITY = "Purbakhola Rural Municipality",
     BAGNASKALI_RURAL_MUNICIPALITY = "Bagnaskali Rural Municipality",
     RAINADEVI_CHHARA_RURAL_MUNICIPALITY = "Rainadevi Chhara Rural Municipality",
     TANSEN_MUNICIPALITY = "Tansen Municipality",
     RAMPUR_MUNICIPALITY = "Rampur Municipality",
 
     // Dang
     BABAI_RURAL_MUNICIPALITY = "Babai Rural Municipality",
     GADHAWA_RURAL_MUNICIPALITY = "Gadhawa Rural Municipality",
     RAPTI_RURAL_MUNICIPALITY = "Rapti Rural Municipality",
     RAJPUR_RURAL_MUNICIPALITY = "Rajpur Rural Municipality",
     DANGISHARAN_RURAL_MUNICIPALITY = "Dangisharan Rural Municipality",
     SHANTINAGAR_RURAL_MUNICIPALITY = "Shantinagar Rural Municipality",
     BANGLACHULI_RURAL_MUNICIPALITY = "Banglachuli Rural Municipality",
     TULSIPUR_SUB_METROPOLITAN_CITY = "Tulsipur Sub-Metropolitan City",
     GHORAHI_SUB_METROPOLITAN_CITY = "Ghorahi Sub-Metropolitan City",
     LAMAHI_MUNICIPALITY = "Lamahi Municipality",
 
     // Pyuthan
     AYIRABATI_RURAL_MUNICIPALITY = "Ayirabati Rural Municipality",
     GAUMUKHI_RURAL_MUNICIPALITY = "Gaumukhi Rural Municipality",
     JHIMRUK_RURAL_MUNICIPALITY = "Jhimruk Rural Municipality",
     NAUBAHINI_RURAL_MUNICIPALITY = "Naubahini Rural Municipality",
     MANDAVI_RURAL_MUNICIPALITY = "Mandavi Rural Municipality",
     MALLARANI_RURAL_MUNICIPALITY = "Mallarani Rural Municipality",
     SARUMARANI_RURAL_MUNICIPALITY = "Sarumarani Rural Municipality",
     PYUTHAN_MUNICIPALITY = "Pyuthan Municipality",
     SWORGADWARY_MUNICIPALITY = "Sworgadwary Municipality",
 
     // Rolpa
    //  MADI_RURAL_MUNICIPALITY = "Madi Rural Municipality", // Also in Kaski
     THAWANG_RURAL_MUNICIPALITY = "Thawang Rural Municipality",
     SUNCHHAHARI_RURAL_MUNICIPALITY = "Sunchhahari Rural Municipality",
     LUNGRI_RURAL_MUNICIPALITY = "Lungri Rural Municipality",
     GANGADEVA_RURAL_MUNICIPALITY = "Gangadev Rural Municipality",
     TRIBENI_RURAL_MUNICIPALITY = "Tribeni Rural Municipality",
     PARIWARTAN_RURAL_MUNICIPALITY = "Pariwartan Rural Municipality",
     RUNTIGADI_RURAL_MUNICIPALITY = "Runtigadi Rural Municipality",
     SUNIL_SMRITI_RURAL_MUNICIPALITY = "Sunil Smriti Rural Municipality",
     ROLPA_MUNICIPALITY = "Rolpa Municipality",
 
     // Eastern Rukum
     BHUME_RURAL_MUNICIPALITY = "Bhume Rural Municipality",
     SISNE_RURAL_MUNICIPALITY = "Sisne Rural Municipality",
     PUTHA_UTTARGANGA_RURAL_MUNICIPALITY = "Putha Uttarganga Rural Municipality",
 
     // Banke
     KHAJURA_RURAL_MUNICIPALITY = "Khajura Rural Municipality",
     JANKI_RURAL_MUNICIPALITY = "Janki Rural Municipality",
     BAIJNATH_RURAL_MUNICIPALITY = "Baijanath Rural Municipality",
     DUDUWA_RURAL_MUNICIPALITY = "Duduwa Rural Municipality",
     NARAINAPUR_RURAL_MUNICIPALITY = "Narainapur Rural Municipality",
     RAPTI_SONARI_RURAL_MUNICIPALITY = "Rapti Sonari Rural Municipality",
     KOHALPUR_MUNICIPALITY = "Kohalpur Municipality",
     NEPALGUNJ_SUB_METROPOLITAN_CITY = "Nepalgunj Sub-Metropolitan City",
 
     // Bardiya
     GERUWA_RURAL_MUNICIPALITY = "Geruwa Rural Municipality",
     BADHAIYATAL_RURAL_MUNICIPALITY = "Badhaiyatal Rural Municipality",
     THAKURBABA_MUNICIPALITY = "Thakurbaba Municipality",
     BANSAGADHI_MUNICIPALITY = "Bansagadhi Municipality",
     BARBARDIYA_MUNICIPALITY = "Barbardiya Municipality",
     RAJAPUR_MUNICIPALITY = "Rajapur Municipality",
     MADHUWAN_MUNICIPALITY = "Madhuwan Municipality",
     GULARIYA_MUNICIPALITY = "Gulariya Municipality",


}