export enum Municipal {
    // Koshi Province:
    
    // Bhojpur
    ARUN = "Arun",
    AAMCHOWK = "Aamchowk",
    HATUWAGADHI = "Hatuwagadhi",
    PAUWADUNGMA = "Pauwadungma",
    TEMKEMAIYUNG = "Temkemaiyung",
    SALPASILICHHO = "Salpasilichho",
    RAMPRASADRAI = "Ramprasad Rai",
    SHADANANDA = "Shadananda",
    BHOJPUR = "Bhojpur",

    // Dhankuta
    CHAUBISE = "Chaubise",
    SHAIDBHUMI = "Shahidbhumi",
    SANGURIGADHI = "Sangurigadhi",
    CHHATHARJORPATI = "Chhathar Jorpati",
    PAKHRIBAS = "Pakhribas",
    MAHALAXMI = "Mahalaxmi",
    DHANKUTA = "Dhankuta",

    // Ilam
    RONG = "Rong",
    MANGSEBUNG = "Mangsebung",
    CHULACHULI = "Chulachuli",
    SANDAKPUR = "Sandakpur",
    FAKPHOKTHUM = "Fakphokthum",
    MAIJOGMAI = "Maijogmai",
    ILLAM = "Illam",
    MAI = "Mai",
    DEUMAI = "Deumai",
    SURYODAYA = "Suryodaya",
    
    // Jhapa
    KAMAL = "Kamal",
    JHAPA = "Jhapa",
    KACHANKAWAL = "Kachankawal",
    GAURIGANJ = "Gauriganj",
    BARHADASHI = "Barhadashi",
    HALDIBARI = "Haldibari",
    BUDDHASHANTI = "Buddhashanti",
    SHIVASATAXI = "Shivasataxi",
    BHADRAPUR = "Bhadrapur",
    KANKAI = "Kankai",
    BIRTAMOD = "Birtamod",
    MECHINAGAR = "Mechinagar",
    DAMAK = "Damak",
    ARJUNDHARA = "Arjundhara",
    GAURADHAHA = "Gauradhaha",

    // Khotang
    SAKELA = "Sakela",
    KHOTEHANG = "Khotehang",
    BARAHAPOKHARI = "Barahapokhari",
    AINSELUKHARK = "Ainselukhark",
    RAWABESI = "Rawa Besi",
    KEPILASAGADHI = "Kepilasagadhi",
    JANTEDHUNGA = "Jantedhunga",
    DIPRUNGCHUICHUMMA = "Diprung Chuichumma",
    HALESITUWACHUNG = "Halesi Tuwachung",
    DIKTELRUPAKOTMAJHUWAGADHI = "Diktel Rupakot Majhuwagadhi",

    // Morang
    JAHADA = "Jahada",
    KATAHARI = "Katahari",
    GRAMTHAN = "Gramthan",
    DHANPALTHAN = "Dhanpalthan",
    KERABARI = "Kerabari",
    BUDHIGANGA = "Budhiganga",
    KANEPOKHARI = "Kanepokhari",
    MIKLAJUNG = "Miklajung",
    LETANG = "Letang",
    SUNWARSHI = "Sunwarshi",
    RANGELI = "Rangeli",
    PATAHRISHANISHCHARE = "Patahrishanishchare",
    BIRATNAGAR = "Biratnagar Metropolitian City",
    URALABARI = "Uralabari",
    BELBARI = "Belbari",
    SUNDARHARAICHA = "Sundarharaicha",
    RATUWAMAI = "Ratuwamai",

    // Okhaldhunga
    LIKHU = "Likhu",
    MOLUNG = "Molung",
    SUNKOSHI = "Sunkoshi",
    CHAMPADEVI = "Champadevi",
    CHISANKHUGADHI = "Chisankhugadhi",
    KHIJIDEMBA = "Khijidemba",
    MANEBHANJYANG = "Manebhanjyang",
    SIDDHICHARAN = "Siddhicharan",

    // Panchthar
    YANGWARAK = "Yangwarak",
    HILIHANG = "Hilihang",
    FALELUNG = "Falelung",
    TUMBWEWA = "Tumbewa",
    KUMMAYAK = "Kummayak",
    MIKLAJUNG_1 = "Miklajung (1)",
    FALGUNANDA = "Falgunanda",
    PHIDIM = "Phidim",

    // Sankhuwasabha
    MAKALU = "Makalu",
    CHICHILA = "Chichila",
    SILICHONG = "Silichong",
    BHOTKHOLA = "Bhotkhola",
    SABHAPOKHARI = "Sabhapokhari",
    DHARMADEVI = "Dharmadevi",
    MADI = "Madi",
    PANCHAKHAPAN = "Panchakhapan",
    CHAINPUR = "Chainpur",
    KHANDBARI = "Khandbari",

    // Solukhumbu
    SOTANG = "Sotang",
    MAHAKULUNG = "Mahakulung",
    LIKHUPIKE = "Likhupike",
    NECHASALYAN = "Nechasalyan",
    THULUNG_DUDHKOSHI = "Thulung Dudhkoshi",
    MAAPYA_DUDHKOSHI = "Maapya Dudhkoshi",
    KHUMBUPASANGLAHMU = "Khumbupasanglahmu",
    SOLUDUDHAKUNDA = "Solududhakunda",

    // Sunsari
    GADHI = "Gadhi",
    KOSHI = "Koshi",
    BARJU = "Barju",
    HARINAGAR = "Harinagar",
    DEWANGANJ = "Dewanganj",
    BHOKRAHA_NARSING = "Bhokraha Narsing",
    RAMDHUNI = "Ramdhuni",
    BARAHCHHETRA = "Barahchhetra",
    DUHABI = "Duhabi",
    INARUWA = "Inaruwa",
    DHARAN = "Dharan",
    ITAHARI = "Itahari",

    // Taplejung
    SIDINGBA = "Sidingba",
    MERINGDEN = "Meringden",
    MAIWAKHOLA = "Maiwakhola",
    PHAKTANGLUNG = "Phaktanglung",
    SIRIJANGHA = "Sirijangha",
    MIKWAKHOLA = "Mikwakhola",
    AATHRAI_TRIBENI = "Aathrai Tribeni",
    PATHIVARA_YANGWARAK = "Pathivara Yangwarak",
    PHUNGLING = "Phungling",

    // Tehrathum
    CHHATHAR = "Chhathar",
    PHEDAP = "Phedap",
    AATHRAI = "Aathrai",
    MENCHAYAM = "Menchayam",
    LALIGURANS = "Laligurans",
    MYANGLUNG = "Myanglung",

    // Udayapur
    TAPLI = "Tapli",
    RAUTAMAI = "Rautamai",
    UDAYAPURGADHI = "Udayapurgadhi",
    LIMCHUNGBUNG = "Limchungbung",
    CHAUDANDIGADHI = "Chaudandigadhi",
    TRIYUGA = "Triyuga",
    KATARI = "Katari",
    BELAKA = "Belaka",


    // Madhesh Pradesh:

    // Sarlahi
    DHANKAUL = "Dhankaul",
    PARSA = "Parsa",
    BISHNU = "Bishnu",
    RAMNAGAR = "Ramnagar",
    KAUDENA = "Kaudena",
    BASBARIYA = "Basbariya",
    CHANDRANAGAR = "Chandranagar",
    CHAKRAGHATTA = "Chakraghatta",
    BRAMHAPURI = "Bramhapuri",
    BARAHATHAWA = "Barahathawa",
    HARIPUR = "Haripur",
    ISHWORPUR = "Ishworpur",
    LALBANDI = "Lalbandi",
    MALANGAWA = "Malangawa",
    KABILASI = "Kabilasi",
    BAGMATI = "Bagmati",
    HARIWAN = "Hariwan",
    BALARA = "Balara",
    HARIPURWA = "Haripurwa",
    GODAITA = "Godaita",

    // Dhanusha
    AAURAHI = "Aaurahi",
    DHANAUJI = "Dhanauji",
    BATESHWOR = "Bateshwor",
    JANAKNANDANI = "Janaknandani",
    LAKSHMINIYA = "Lakshminiya",
    MUKHIYAPATTI_MUSARMIYA = "Mukhiyapatti Musarmiya",
    MITHILA_BIHARI = "Mithila Bihari",
    KAMALA = "Kamala",
    NAGARAIN = "Nagarain",
    GANESHMAN_CHARNATH = "Ganeshman Charnath",
    MITHILA = "Mithila",
    DHANUSADHAM = "Dhanusadham",
    BIDEHA = "Bideha",
    SABAILA = "Sabaila",
    HANSAPUR = "Hansapur",
    JANAKPURDHAM_SUB_METROPOLITIAN = "Janakpurdham Sub-Metropolitan City",
    SAHIDNAGAR = "Sahidnagar",
    CHHIRESHWORNATH = "Chhireshwornath",

    // Bara
    PHETA = "Pheta",
    DEVTAL = "Devtal",
    PRASAUNI = "Prasauni",
    SUWARNA = "Suwarna",
    BARAGADHI = "Baragadhi",
    KARAIYAMAI = "Karaiyamai",
    PARWANIPUR = "Parwanipur",
    BISHRAMPUR = "Bishrampur",
    ADARSHKOTWAL = "Adarshkotwal",
    JITPUR_SIMARA_SUB_METROPOLITIAN = "Jitpur Simara Sub-Metropolitan City",
    KALAIYA_SUB_METROPOLITIAN = "Kalaiya Sub-Metropolitan City",
    PACHARAUTA = "Pacharauta",
    NIJGADH = "Nijgadh",
    SIMRAUNGADH = "Simraungadh",
    MAHAGADHIMAI = "Mahagadhimai",
    KOLHABI = "Kolhabi",

    // Rautahat
    YEMUNAMAI = "Yemunamai",
    DURGA_BHAGWATI = "Durga Bhagwati",
    KATAHARIYA = "Katahariya",
    MAULAPUR = "Maulapur",
    MADHAV_NARAYAN = "Madhav Narayan",
    GAUR = "Gaur",
    GUJARA = "Gujara",
    GARUDA = "Garuda",
    ISHANATH = "Ishanath",
    CHANDRAPUR = "Chandrapur",
    DEWAHHI_GONAHI = "Dewahhi Gonahi",
    BRINDABAN = "Brindaban",
    RAJPUR = "Rajpur",
    RAJDEVI = "Rajdevi",
    GADHIMAI = "Gadhimai",
    PHATUWA_BIJAYAPUR = "Phatuwa Bijayapur",
    BAUDHIMAI = "Baudhimai",
    PAROHA = "Paroha",

    // Saptari
    RAJGADH = "Rajgadh",
    RUPANI = "Rupani",
    TIRAHIUT = "Tirahut",
    MAHADEVA = "Mahadeva",
    BISHNUPUR_RURAL = "Bishnupur Rural",
    CHHINNAMASTA = "Chhinnamasta",
    BALAN_BIHUL = "Balan Bihul",
    TILATHI_KOILADI = "Tilathi Koiladi",
    AGNISAIR_KRISHNA_SAVARAN = "Agnisair Krishna Savaran",
    HANUMANNAGAR_KANKALINI = "Hanumannagar Kankalini",
    KANCHANRUP = "Kanchanrup",
    RAJBIRAJ = "Rajbiraj",
    KHADAK = "Khadak",
    DAKNESHWORI = "Dakneshwori",
    SAPTAKOSHI = "Saptakoshi",
    SURUNGA = "Surunga",
    SHAMBHUNATH = "Shambhunath",
    BODE_BARSAIN = "Bode Barsain",

    // Siraha
    AURAHI_Rural = "Aurahi Rural",
    NARAHA = "Naraha",
    ARNAMA = "Arnama",
    BHAGAWANPUR = "Bhagawanpur",
    NAWARAJPUR = "Nawarajpur",
    BISHNUPUR = "Bishnupur",
    BARIYARPATTI = "Bariyarpatti",
    LAXMIPUR_PATARI = "Laxmipur Patari",
    SAKHUWANANKARKATTI = "Sakhuwanankarkatti",
    MIRCHAIYA = "Mirchaiya",
    LAHAN = "Lahan",
    SIRAHA = "Siraha",
    DHANGADHIMAI = "Dhangadhimai",
    KALYANPUR = "Kalyanpur",
    KARJANHA = "Karjanha",
    GOLBAZAR = "Golbazar",
    SUKHIPUR = "Sukhipur",

    // Mahottari
    PIPRA = "Pipra",
    SONAMA = "Sonama",
    SAMSI = "Samsi",
    EKDANRA = "Ekdandra",
    MAHOTTARI = "Mahottari",
    GAUSHALA = "Gaushala",
    RAMGOPALPUR = "Ramgopalpur",
    AURAHI = "Aurahi",
    BARDIBAS = "Bardibas",
    BHANGAHA = "Bhangaha",
    JALESWOR = "Jaleswor",
    BALWA = "Balwa",
    MANRA_SISWA = "Manra Siswa",
    MATIHANI = "Matihani",
    LOHARPATTI = "Loharpatti",

    // Parsa
    THORI = "Thori",
    DHOBINI = "Dhobini",
    CHHIPAHARMAI = "Chhipaharmai",
    JIRABHAWANI = "Jirabhawani",
    JAGARNATHPUR = "Jagarnathpur",
    KALIKAMAI = "Kalikamai",
    BINDABASINI = "Bindabasini",
    PAKAHAMAINPUR = "Pakahamainpur",
    SAKHUWAPRASAUNI = "Sakhuwaprasauni",
    PATERWASUGAULI = "Paterwasugauli",
    BIRGUNJ_METROPOLITIAN_CITY = "Birgunj Metropolitian City",
    BAHUDARAMAI = "Bahudaramai",
    POKHARIYA = "Pokhariya",
    PARSAGADHI = "Parsagadhi",

    // Bagmati Pradesh

    // Sindhuli
}